
using Hec.Entities;
using Hec.IdGeneration;
using Hec.Workflows;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Threading.Tasks;

namespace Hec.Migrations
{
    public partial class Configuration
    {

        private void SeedAppliance(HecContext db)
        {
            // From file Appliances - New Default Values - v2.xlsx
            db.Appliances.AddOrUpdate(
                x => x.Name,
                new Appliance { Name = "Air Condition", DefaultHoursPerDay = 5, DefaultDaysPerMonth = 15, DefaultWatts = 746, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = true, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Air Conditioner").Id },
                new Appliance { Name = "Fan", DefaultHoursPerDay = 8, DefaultDaysPerMonth = 30, DefaultWatts = 50, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = true, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Air Conditioner").Id },
                new Appliance { Name = "Light", DefaultHoursPerDay = 8, DefaultDaysPerMonth = 30, DefaultWatts = 32, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = true, ForDiningRoom = true, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Lighting").Id },
                new Appliance { Name = "Television", DefaultHoursPerDay = 2, DefaultDaysPerMonth = 30, DefaultWatts = 50, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = true, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Astro Decoder", DefaultHoursPerDay = 2, DefaultDaysPerMonth = 30, DefaultWatts = 20, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Hypp TV Decoder", DefaultHoursPerDay = 2, DefaultDaysPerMonth = 30, DefaultWatts = 20, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "DVD Player", DefaultHoursPerDay = 3, DefaultDaysPerMonth = 4, DefaultWatts = 15, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "HI-FI", DefaultHoursPerDay = 2, DefaultDaysPerMonth = 30, DefaultWatts = 75, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Game Console", DefaultHoursPerDay = 2, DefaultDaysPerMonth = 30, DefaultWatts = 90, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Fridge", DefaultHoursPerDay = 24, DefaultDaysPerMonth = 30, DefaultWatts = 400, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Fridge").Id },
                new Appliance { Name = "Chest Freezer", DefaultHoursPerDay = 24, DefaultDaysPerMonth = 30, DefaultWatts = 500, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Fridge").Id },
                new Appliance { Name = "Electric Kettle", DefaultHoursPerDay = 0.25m, DefaultDaysPerMonth = 30, DefaultWatts = 1000, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Kettle").Id },
                new Appliance { Name = "Toaster", DefaultHoursPerDay = 0.1m, DefaultDaysPerMonth = 30, DefaultWatts = 700, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Kettle").Id },
                new Appliance { Name = "Bread Maker", DefaultHoursPerDay = 2, DefaultDaysPerMonth = 5, DefaultWatts = 480, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Kettle").Id },
                new Appliance { Name = "Rice Cooker", DefaultHoursPerDay = 0.5m, DefaultDaysPerMonth = 20, DefaultWatts = 700, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Induction Cooker", DefaultHoursPerDay = 0.1m, DefaultDaysPerMonth = 15, DefaultWatts = 1000, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Oven", DefaultHoursPerDay = 0.5m, DefaultDaysPerMonth = 4, DefaultWatts = 1000, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Microwave").Id },
                new Appliance { Name = "Microwave", DefaultHoursPerDay = 0.5m, DefaultDaysPerMonth = 20, DefaultWatts = 600, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Microwave").Id },
                new Appliance { Name = "Stand Mixer", DefaultHoursPerDay = 0.5m, DefaultDaysPerMonth = 2, DefaultWatts = 200, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Dishwasher", DefaultHoursPerDay = 0.5m, DefaultDaysPerMonth = 15, DefaultWatts = 1200, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Washing Machine", DefaultHoursPerDay = 1, DefaultDaysPerMonth = 20, DefaultWatts = 500, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Washing Machine").Id },
                new Appliance { Name = "Dryer", DefaultHoursPerDay = 1, DefaultDaysPerMonth = 6, DefaultWatts = 3400, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "Washing Machine").Id },
                new Appliance { Name = "Electric Iron", DefaultHoursPerDay = 0.5m, DefaultDaysPerMonth = 15, DefaultWatts = 750, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Clothes Steamer", DefaultHoursPerDay = 0.5m, DefaultDaysPerMonth = 15, DefaultWatts = 1000, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Vacuum Cleaner", DefaultHoursPerDay = 0.5m, DefaultDaysPerMonth = 4, DefaultWatts = 400, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = false, ForBedroom = false, ForBathroom = false, ForDiningRoom = false, ForKitchen = true , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Desktop PC", DefaultHoursPerDay = 4, DefaultDaysPerMonth = 30, DefaultWatts = 300, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Laptop", DefaultHoursPerDay = 4, DefaultDaysPerMonth = 30, DefaultWatts = 50, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Printer", DefaultHoursPerDay = 0.1m, DefaultDaysPerMonth = 4, DefaultWatts = 75, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Router", DefaultHoursPerDay = 24, DefaultDaysPerMonth = 30, DefaultWatts = 10, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Scanner", DefaultHoursPerDay = 0.1m, DefaultDaysPerMonth = 2, DefaultWatts = 20, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Phone Charger", DefaultHoursPerDay = 6, DefaultDaysPerMonth = 30, DefaultWatts = 10, DefaultNumbersOfApp = 1, ForLivingRoom = true, ForMasterBedroom = true, ForBedroom = true, ForBathroom = false, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Hair Dryer", DefaultHoursPerDay = 0.5m, DefaultDaysPerMonth = 15, DefaultWatts = 1000, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = true, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Electric Shaver", DefaultHoursPerDay = 0.1m, DefaultDaysPerMonth = 30, DefaultWatts = 15, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = true, ForDiningRoom = false, ForKitchen = false , TipCategoryId = db.TipCategories.First(x => x.Name == "General").Id },
                new Appliance { Name = "Water Heater", DefaultHoursPerDay = 0.5m, DefaultDaysPerMonth = 30, DefaultWatts = 1000, DefaultNumbersOfApp = 1, ForLivingRoom = false, ForMasterBedroom = false, ForBedroom = false, ForBathroom = true, ForDiningRoom = false, ForKitchen = false, TipCategoryId = db.TipCategories.First(x => x.Name == "Water Heater").Id }
            );

            db.SaveChanges();
        }
    }
}
