window.translations = {
    lang: "en",
    "default": "Default",
    "delete": "Delete",
    stakeholder_expectation_tooltip: "Expectation from stakeholders on unit's/department's services or products",
    outcome_tooltip: "Which areas of the expectation that need to enhance or change to achieve department's/Division's aspiration and bring positive impact to stakeholder",
    key_result_area_tooltip: "KRA identified that is aligned/supported by the strategies",
    strategy_tooltip: "What we need to strategize to influence and achieve the Outcome",
    indicator_tooltip: "Indicator to measure the effectiveness of the Outcome",
    target_tooltip: "Range of Meeting Target",
    weightage_tooltip: "% priority of Outcome-Based KPI",
    enabler_health_tooltip: "Indicator to measure the enablers of the Outcome & Condition/health of the organization",
    target_enablerhealth_tooltip: "Target for enabler and health",
    login: "Login",
    logout: "Logout",
    staff_details: "Staff Details",
    staff_name: "Staff Name",
    email: "Email",
    contact_no: "Contact No",
    grade: "Grade",
    job: "Job",
    division: "Division",
    department: "Department",
    position: "Position",
    position_level: "Position Level",
    imanager_name: "Immediate Manager Name",
    previous_imanager: "Previous Immediate Manager",
    change_photo: "Change Photo",
    change_password: "Change Password",
    preferences: "Language Preference",
    default_language: "Default Language",
    error: "Error",
    cannot_retrieve_current_user_information: "Cannot retrieve current user information",
    error_message: "Error Message",
    welcome: "Welcome",
    finish: "Finish",
    kpi_setting_for: "KPI Setting for",
    the_kpi_setting_module_for_this_cycle_is_closed_kpi_setting_is_not_editable: "The KPI Setting Module for this Cycle is closed. KPI Setting is not editable",
    outcome_based_kpi: "Outcome Based KPI",
    add_new_kpi_and_enabler_health: "Add New KPI and Enabler-Health",
    add_new_enabler_health_only: "Add New Enabler Health Only",
    stakeholder_expectation: "Stakeholder Expectation",
    outcome: "Outcome",
    strategy_by_kra: "Strategy by KRA",
    enabler_health: "Enabler-Health",
    indicator: "Indicator",
    target: "Target",
    indpeer: "Ind/Peer",
    total_weightage: "Total Weightage",
    add_new_technical_competency: "Add New Technical Competency",
    technical_competency: "Technical Competency",
    category: "Category",
    technical_label: "Technical Label",
    level: "Level",
    description: "Description",
    action: "Action",
    criteria_to_be_fulfilled_self: "Criteria to be Fulfilled (Self)",
    criteria_to_be_fulfilled_imanager: "Criteria to be Fulfilled (Immediate Manager)",
    submit: "Submit",
    define: "Define",
    logs: "Logs",
    print: "Print",
    kpi_setting: "KPI Setting",
    show: "Show",
    kpi: "KPI",
    cascade: "Cascade",
    cascaded: "Cascaded",
    undo_cascade: "Undo Cascade",
    remove: "Remove",
    individual: "Individual",
    peer: "Peer",
    yes: "Yes",
    no: "No",
    kpi_cannot_be_submitted_if_these_criteria_are_not_met: "KPI cannot be submitted if these criteria are not met",
    kpi_cannot_be_defined_if_these_criteria_are_not_met: "KPI cannot be defined if these criteria are not met",
    passed: "Passed",
    not_passed: "Not Passed",
    edit: "Edit",
    show_profile: "Show Profile",
    hide_profile: "Hide Profile",
    draft: "Draft",
    submitted: "Submitted",
    defined: "Defined",
    is_required: "is required",
    kpi_type: "KPI Type",
    stakeholder: "Stakeholder",
    key_result_area_kra: "Key Result Area (KRA)",
    strategy_by_key_result_area: "Strategy By Key Result Area",
    key_performance_indicator: "Key Performance Indicator",
    target_kpi: "Target KPI",
    lower_mt: "Lower MT",
    upper_mt: "Upper MT",
    weightage: "Weightage",
    save: "Save",
    select: "Select",
    some_error_occured_please_try_again: "Some error occured. Please try again.",
    there_are_some_errors_please_check_your_input: "There are some errors, please check your input.",
    some_error_occured_while_saving_enabler_health_please_try_again: "Some error occured while saving Enabler-Health. Please try again.",
    kpi_has_been_successfully_added: "KPI has been successfully added.",
    administration: "Administration",
    cycle_management: "Cycle Management",
    user_management: "User Management",
    usergroup_management: "Usergroup Management",
    user_registrations: "User Registrations",
    forgotten_password: "Forgotten Password",
    email_template: "Email Template",
    technical_categorylabel: "Technical Category/Label",
    job_management: "Job Management",
    position_management: "Position Management",
    grade_management: "Grade Management",
    divisiondepartment: "Division/Department",
    personnel_areasub_area: "Personnel Area/Sub-Area",
    stakeholder_expectations: "Stakeholder Expectations",
    position_level_management: "Position Level Management",
    invalid_target_management: "Invalid Target Management",
    email_queue: "Email Queue",
    system_configuration: "System Configuration",
    management_report: "Management Report",
    performance_plan_status: "Performance Plan Status",
    not_submitted_self: "Not Submitted - Self",
    submitted_self: "Submitted - Self",
    incomplete_imgr: "Incomplete - IMgr",
    complete_imgr: "Complete - IMgr",
    obits_cycle: "OBITS Cycle",
    library: "Library",
    user_training: "User Training",
    cycle_info: "Cycle Info",
    edit_kpi_and_enabler_health: "Edit KPI and Enabler-Health",
    kpi_has_been_successfully_edited: "KPI has been successfully edited",
    new_enabler_health_record_has_been_successfully_created: "New Enabler-Health record has been successfully created.",
    text: "Text",
    division_management: "Division Management",
    subsidiary: "Subsidiary",
    active: "Active",
    deleted: "Deleted",
    view_department: "View Department",
    department_management: "Department Management",
    type: "Type",
    supervisor: "Supervisor",
    send_emails_now: "Send Emails Now",
    subject: "Subject",
    to: "To",
    sent_on: "Sent On",
    processed_on: "Processed On",
    created_on: "Created On",
    scheduled_on: "Scheduled On",
    view_technical_competencies: "View Technical Competencies",
    technical_category: "Technical Category",
    proficiency_level: "Proficiency Level",
    default_technical_competency_management: "Default Technical Competency Management",
    add_technical_competency: "Add Technical Competency",
    edit_technical_competency: "Edit Technical Competency",
    concept: "Concept",
    applying: "Applying",
    working: "Working",
    advanced: "Advanced",
    mastery: "Mastery",
    leading: "Leading",
    personnel_area_management: "Personnel Area Management",
    view_sub_areas: "View Sub-Areas",
    personnel_sub_area_management: "Personnel Sub-Area Management",
    area: "Area",
    view_users: "View Users",
    position_level_users_management: "Position Level Users Management",
    staff_no: "Staff No",
    add_user_to_position_level: "Add User to Position Level",
    search_for_a_staff_using_the_search_box_below: "Search for a Staff using the search box below.",
    enter_staff_number_or_name: "Enter Staff Number or Name",
    search: "Search",
    some_error_occured_while_saving_enabler_health_indicatortarget_please_try_again: "Some error occured while saving Enabler-Health Indicator/Target. Please try again.",
    add_enabler_health_only: "Add Enabler-Health Only",
    you_must_have_at_least_one_indicatortarget: "You must have at least one Indicator/Target.",
    edit_enabler_health_only: "Edit Enabler-Health Only",
    enabler_health_has_been_successfully_updated: "Enabler-Health has been successfully updated",
    technical_category_management: "Technical Category Management",
    view_labels: "View Labels",
    technical_label_management: "Technical Label Management",
    definition: "Definition",
    datetime: "Date/Time",
    status: "Status",
    division_id: "Division ID",
    division_name: "Division Name",
    phone_no: "Phone No",
    remarks: "Remarks",
    create_user: "Create User",
    view_user: "View User",
    forgotten_password_logs: "Forgotten Password Logs",
    password_reset: "Password reset",
    remarks_only: "Remarks only",
    view_forgotten_password_logs: "View forgotten password logs",
    user_not_found: "User not found",
    nric: "NRIC",
    reset_password: "Reset Password",
    add_remarks_only: "Add Remarks Only",
    user_login_type_is_active_directory_contact_email_administrator_for_password_management_operations: "User Login Type is Active Directory. Contact email administrator for password management operations.",
    save_remarks: "Save Remarks",
    user_password_has_been_reset_to: "User password has been reset to",
    by: "By",
    are_you_sure_to_reset_users_password: "Are you sure to reset user's password?",
    role: "Role",
    self: "Self",
    imanager: "Immediate Manager",
    staff: "Staff",
    view: "View",
    kpi_templates: "KPI Templates",
    cycle: "Cycle",
    current: "Current",
    completed: "Completed",
    edit_usergroup: "Edit Usergroup",
    create_new_usergroup: "Create New Usergroup",
    usergroup_name: "Usergroup Name",
    users: "Users",
    technical_competency_has_been_successfully_added: "Technical Competency has been successfully added",
    technical_competency_has_been_successfully_updated: "Technical Competency has been successfully updated",
    performance_plan_template: "Performance Plan Template",
    performance_template: "Performance Template",
    view_performance_plan: "View Performance Plan",
    kpi_template_cannot_be_copied_to_subordinates_if_these_criteria_are_not_met: "KPI Template cannot be copied to subordinates if these criteria are not met",
    error_calculating_weightage_please_try_again: "Error calculating weightage. Please try again.",
    kpi_has_been_successfully_deleted: "KPI has been successfully deleted.",
    technical_competency_has_been_successfully_deleted: "Technical Competency has been successfully deleted.",
    enabler_health_has_been_successfully_deleted: "Enabler-Health has been successfully deleted.",
    create_new_user: "Create New User",
    user_type: "User Type",
    fetch_ad_information: "Fetch AD Information",
    re_type_password: "Re-Type Password",
    retire_date: "Retire Date",
    employment_status: "Employment Status",
    job_status: "Job Status",
    define_kpi_type: "Define KPI type",
    enabled: "Enabled",
    disabled: "Disabled",
    usergroup: "Usergroup",
    assign_imgr: "Assign IMgr",
    sub_area: "Sub-Area",
    login_type: "Login Type",
    no_photo: "No photo",
    edit_user: "Edit User",
    never: "Never",
    last_login: "Last Login",
    first_time_login: "First Time Login",
    job_details: "Job Details",
    change: "Change",
    performance_plans: "Performance Plans",
    assign_new_immediate_manager: "Assign New Immediate Manager",
    sequence: "Sequence",
    set_as_current: "Set as Current",
    personnel_area: "Personnel Area",
    personnel_sub_area: "Personnel Sub-Area",
    kpi_plan_template_successfully_copied_to_all_subordinates: "KPI Plan Template successfully copied to all subordinates",
    failed_to_copy_kpi_plan_template_to_some_subordinates: "Failed to copy KPI Plan Template to some subordinates.",
    please_select_a_cycle: "Please select a Cycle",
    kpi_plan_has_been_successfully_submitted: "KPI plan has been successfully submitted.",
    kpi_plan_has_been_successfully_defined: "KPI plan has been successfully defined.",
    you_have_reached_maximum_number_of_total_technical_competencies: "You have reached maximum number of total Technical Competencies.",
    the_selected_peer_kpi_has_been_successfully_removed_from_your_subordinates_kpi_plan: "The selected Peer KPI has been successfully removed from your subordinates KPI Plan",
    view_kpi_plan: "View KPI Plan",
    selected_kpi_will_be_deleted_click_ok_to_confirm: "Selected KPI will be deleted. Click OK to confirm.",
    selected_technical_competency_will_be_deleted_click_ok_to_confirm: "Selected Technical Competency will be deleted. Click OK to confirm.",
    selected_enabler_health_will_be_deleted_click_ok_to_confirm: "Selected Enabler-Health will be deleted. Click OK to confirm.",
    kpi_plan_will_be_submitted_click_ok_to_confirm: "KPI plan will be submitted. Click OK to confirm.",
    kpi_plan_will_be_defined_click_ok_to_confirm: "KPI plan will be defined. Click OK to confirm.",
    alert_total_weightage_exceeds: "Alert: Total weightage exceeds ",
    alert_total_weightage_exceeds_100: "Alert: Total weightage exceeds 100%",
    job_is_required: "Job is required",
    stakeholder_expectation_is_required: "Stakeholder Expectation is required",
    rule_mandatory_fields: "All mandatory fields must be filled",
    rule_individual_kpi_count: "Individual KPI - minimum : {0} maximum: {1}",
    rule_peer_kpi_count: "Peer KPI - minimum : {0} maximum: {1}",
    rule_technical_competency_count: "Technical Competency - minimum : {0} maximum: {1}",
    rule_individual_weight_total: "Individual Total Weightage - minimum: {0} maximum: {1}",
    rule_all_kpi_count: "Total KPI - minimum: {0} maximum: {1}",
    rule_weight_100: "Total weightage must be 100%",
    outcome_is_required: "Outcome is required",
    key_result_area_is_required: "Key Result Area is required",
    strategy_by_key_result_area_is_required: "Strategy By Key Result Area is required",
    key_performance_indicator_is_required: "Key Performance Indicator is required",
    lower_mt_is_required: "Lower MT is required",
    upper_mt_is_required: "Upper MT is required",
    weightage_is_required: "Weightage is required",
    proficiency_level_is_required: "Proficiency Level is required",
    copy_kpi_plan_onto_subordinates: "Copy KPI Plan Onto Subordinates",
    no_subordinates_selected: "No subordinates selected.",
    description_is_required: "Description is Required",
    label_is_required: "Label is Required",
    category_is_required: "Category is Required",
    cascade_kpi_to_subordinates: "Cascade KPI to Subordinates",
    cascade_kpi: "Cascade KPI",
    subordinates: "Subordinates",
    error_cascading_kpi_to: "Error cascading KPI to",
    copy_to_cycle: "Copy to Cycle",
    imgr_to_complete_staffs_kpi_setting: "IMgr to complete staff's KPI Setting",
    attention_a_cascaded_kpi_has_been_selected_for_deletion_deletion_of_this_cascaded_kpi_will_subsequently_delete_the_same_kpi_at_your_subordinates_kpi_planning_and_the_affected_next_level_click_ok_to_confirm: "Attention! A cascaded KPI has been selected for deletion. Deletion of this cascaded KPI will subsequently delete the same KPI at your subordinates KPI Planning and the affected next level. Click OK to confirm.",
    start_cycle_date: "Start Cycle Date",
    end_cycle_date: "End Cycle Date",
    start_module_date: "Start Module Date",
    end_module_date: "End Module Date",
    cycle_name_is_required: "Cycle name is required.",
    start_cycle_date_is_required: "Start Cycle Date is required",
    maximum_weightage_for_self: "% maximum weightage for Self",
    peer_kpi_will_be_removed_from_your_subordinates_kpi_planning_and_subsequently_remove_the_same_kpi_at_the_affected_next_level_click_ok_to_confirm: "Peer KPI will be removed from your subordinates KPI Planning, and subsequently remove the same KPI at the affected next level. Click OK to confirm",
    kpi_and_technical_competency_have_been_successfully_copied: "KPI and Technical Competency have been successfully copied",
    kpi_has_been_successfully_cascaded_to: "KPI has been successfully cascaded to ",
    technical_competency_has_been_successfully_edited: "Technical competency has been successfully edited",
    weight: "Weight",
    end_cycle_date_is_required: "End Cycle Date is required",
    a_new_cycle_will_be_created_click_ok_to_confirm: "A new cycle will be created. Click OK to confirm.",
    end_date_cannot_be_earlier_than_start_date: "End Date cannot be earlier than Start Date.",
    cycle_has_been_saved_successfully: "Cycle has been saved successfully.",
    add_open_to: "Add Open To",
    edit_module: "Edit Module",
    open_to_category: "Open To Category",
    select_a_department: "Select a Department",
    select_a_division: "Select a Division",
    select_a_position_level: "Select a Position Level",
    grade_type: "Grade Type",
    add_open_to_specification: "Add Open To Specification",
    open_to_specifications_has_been_successfully_added_to_module: "Open To specifications has been successfully added to module",
    edit_cycle: "Edit Cycle",
    update: "Update",
    kpi_rules_and_management: "KPI Rules and Management",
    weightage_settings_unit: "Weightage Settings (Unit %)",
    weightage_factor: "Weightage Factor",
    weightage_fraction: "Weightage Fraction",
    numbers_divisible_by_5_separated_by_comma: "(numbers divisible by 5, separated by comma)",
    kpitechnical_competency_count: "KPI/Technical Competency Count",
    for_self: "For Self",
    min: "Min",
    max: "Max",
    individual_kpi_count: "Individual KPI Count",
    technical_competency_total: "Technical Competency Total",
    individual_total_weightage: "Individual Total Weightage",
    for_manager: "For Manager",
    peer_kpi_count: "Peer KPI Count",
    kpi_total: "KPI Total",
    confirm: "Confirm",
    modules: "Modules",
    selection_multi_rater: "Selection Multi Rater",
    yeed: "YEED",
    epa_data_entry: "EPA Data Entry",
    print_notification_letter: "Print Notification Letter",
    appeal_registration: "Appeal Registration",
    appeal_registration_for_pa: "Appeal Registration For PA",
    appeal_data_entry: "Appeal Data Entry",
    print_appeal_letter: "Print Appeal Letter",
    individual_development_plan: "Individual Development Plan",
    minimum_kpi_total_is_required: "Minimum KPI total is required",
    maximum_kpi_total_is_required: "Maximum KPI total is required",
    minimum_peer_kpi_is_required: "Minimum peer KPI is required",
    maximum_peer_kpi_is_required: "Maximum peer KPI is required",
    minimum_weightage_is_required: "Minimum weightage is required",
    maximum_weightage_is_required: "Maximum weightage is required",
    minimum_technical_competency_is_required: "Minimum technical competency is required",
    maximum_technical_competency_is_required: "Maximum technical competency is required",
    minimum_individual_kpi_is_required: "Minimum individual kpi is required",
    maximum_individual_kpi_is_required: "Maximum individual kpi is required",
    cycle_details_will_be_updated_click_ok_to_confirm: "Cycle details will be updated. Click OK to confirm.",
    cycle_has_been_updated_successfully: "Cycle has been updated successfully.",
    technical_competency_total_max_value_must_be_greater_than_min_value: "Technical Competency Total: Max value must be greater than min value.",
    individual_total_weightage_max_value_must_be_greater_than_min_value: "Individual Total Weightage: Max value must be greater than min value.",
    individual_kpi_count_max_value_must_be_greater_than_min_value: "Individual KPI Count: Max value must be greater than min value.",
    peer_kpi_count_max_value_must_be_greater_than_min_value: "Peer KPI Count: Max value must be greater than min value.",
    kpi_total_max_value_must_be_greater_than_min_value: "KPI Total: Max value must be greater than min value.",
    cycle_rule_will_be_confirmed_click_ok_to_confirm: "Cycle rule will be confirmed. Click OK to confirm.",
    cycle_rule_has_been_confirmed_successfully: "Cycle rule has been confirmed successfully.",
    open_to: "Open To",
    open_to_specification: "Open To Specification",
    specification: "Specification",
    start: "Start",
    end: "End",
    this_module_is_now: "This module is now",
    for_this_cycle: "for this Cycle",
    upload_staff_data: "Upload Staff Data",
    add_new_cycle: "Add New Cycle",
    upload_data: "Upload Data",
    staff_detail_file: "Staff Detail File",
    staff_manager_file: "Staff-Manager File",
    start_processing: "Start Processing",
    sending_emails: "Sending emails...",
    current_password: "Current Password",
    new_password: "New Password",
    re_type_new_password_for_confirmation: "Re-Type New Password for Confirmation",
    change: "Change",
    password_cannot_be_empty: "Password cannot be empty.",
    new_password_and_password_confirmation_must_be_the_same: "New password and password confirmation must be the same.",
    password_has_been_changed_successfully: "Password has been changed successfully.",
    upload_photo_jpgjpeg_max_size_100kb: "Upload Photo (.jpg/.jpeg, max size 100kb)",
    please_upload_jpg_files_only: "Please upload JPG files only.",
    file_size_more_than_100kb_is_not_allowed: "File size more than 100kb is not allowed.",
    default_technical_competency_has_been_successfully_edited: "Default Technical Competency has been successfully edited.",
    cycle_information: "Cycle Information",
    content_is_coming_soon: "Content is coming soon.",
    documents: "Documents",
    frequently_asked_questions_faq: "Frequently Asked Questions (FAQ)",
    click_to_download_file: "Click to download file",
    circular: "Circular",
    user_manual_malay: "User Manual (BM)",
    kpi_settings_for_self: "KPI Settings for Self",
    kpi_settings_for_manager: "KPI Settings for Manager",
    user_manual_english: "User Manual",
    overview: "Overview",
    introducing_the_new_kpi_framework_and_information_about_obits: "Introducing the new KPI framework and information about OBITS.",
    video_and_demos: "Videos and Demonstration",
    watch_interactive_video_tutorials_and_product_highlights: "Watch interactive video tutorials and product highlights.",
    faqs_and_documents: "FAQs and Documents",
    get_circular_information_user_manual_and_answers_to_your_faqs: "Get circular information, user manual and answers to your FAQs.",
    obits_introduction: "OBITS Introduction",
    to_view_this_video_please_enable_javascript_and_consider_upgrading_to_a_web_browser_that: "To view this video please enable JavaScript, and consider upgrading to a web browser that",
    supports_html5_video: "supports HTML5 video",
    user_successfully_assigned_to_position_level: "User successfully assigned to Position Level.",
    no_records_found: "No records found.",
    please_enter_keywords_to_search: "Please enter keyword(s) to search.",
    a_new_user_group_will_be_created_click_ok_to_confirm: "A new User Group will be created. Click OK to confirm.",
    usergroup_was_successfully_created_assigned_access_rights_by_clicking_on_the_checkboxes: "Usergroup was successfully created. Assigned Access Rights by clicking on the checkboxes.",
    user_group_detail_will_be_updated_click_ok_to_confirm: "User Group detail will be updated. Click OK to confirm.",
    role_was_successfully_updated: "Role was successfully updated.",
    e_mail_template: "E-Mail Template",
    template_type: "Template Type",
    select_template_type: "Select template type",
    subject_template: "Subject Template",
    content_template: "Content Template",
    preview: "Preview",
    save_template: "Save Template",
    variables: "Variables",
    select_a_template_type_to_see_description: "Select a template type to see description…",
    notification_when_a_module_is_starting: "Notification when a module is starting.",
    notification_when_a_module_is_ending: "Notification when a module is ending.",
    notification_when_a_plan_status_changed_from_completed_to_submitted_because_of_peer_kpi_deletion_or_other_factors: "Notification when a plan status changed from Completed to Submitted because of peer KPI deletion or other factors.",
    password_reset_email_when_user_go_through_the_forgot_password_feature: "Password reset email when user go through the Forgot Password feature.",
    notification_for_administrators_when_a_new_user_registered_into_the_system: "Notification for administrators when a new user registered into the system.",
    error_while_parsing_template: "Error while parsing template!",
    email_template_has_been_saved_successfully: "Email Template has been saved successfully.",
    remarks_has_been_saved_successfully: "Remarks has been saved successfully.",
    assign_immediate_manager: "Assign Immediate Manager",
    manage_user: "Manage User",
    current_immediate_manager: "Current Immediate Manager:",
    select_cycle: "Select cycle:",
    search_for_a_new_immediate_manager_using_the_search_box_below: "Search for a new Immediate Manager using the search box below.",
    search: "Search",
    sub_area: "Sub-Area",
    are_you_sure_to_assign_immediate_manager_for_user: "Are you sure to ASSIGN Immediate Manager for user:",
    current_imgr: "Current IMgr:",
    assign_to_imgr: "Assign to IMgr:",
    user: "User:",
    immediate_manager_assigned_successfully: "Immediate Manager assigned successfully.",
    enter_department: "Enter Department...",
    change_department: "Change Department",
    department_changed_successfully: "Department changed successfully.",
    change_grade: "Change Grade",
    enter_grade: "Enter Grade...",
    grade_changed_successfully: "Grade changed successfully.",
    change_immediate_manager: "Change Immediate Manager",
    current_immediate_manager: " Current Immediate Manager:",
    are_you_sure_to_change_immediate_manager_for_user: "Are you sure to CHANGE Immediate Manager for user:",
    new_imgr: "New IMgr:",
    immediate_manager_changed_successfully: "Immediate Manager changed successfully.",
    change_job: "Change Job",
    job_changed_successfully: "Job changed successfully.",
    password_changed_successfully: "Password changed successfully.",
    change_personnel_sub_area: "Change Personnel Sub-Area",
    enter_personnel_area_or_sub_area: "Enter Personnel Area or Sub-Area...",
    personnel_sub_area_changed_successfully: "Personnel Sub-Area changed successfully.",
    change_position: "Change Position",
    enter_position: "Enter Position...",
    position_changed_successfully: "Position changed successfully.",
    change_position_level: "Change Position Level",
    enter_position_level: "Enter Position Level...",
    position_level_changed_successfully: "Position Level changed successfully.",
    fetching_user_information_from_active_directory: "Fetching user information from Active Directory...",
    cannot_find_staff_with_id: "Cannot find Staff with ID = ",
    already_registered_in_obits: "already registered in OBITS.",
    information_successfully_fetched_from_active_directory: "Information successfully fetched from Active Directory.",
    password_and_password_verification_must_be_the_same: "Password and password verification must be the same.",
    new_user_will_be_created_click_ok_to_confirm: "New user will be created. Click OK to confirm.",
    user_successfully_created_please_proceed_by_setting_job_details: "User successfully created. Please proceed by setting Job Details.",
    fullname_is_required: "FullName is required",
    contact_number_not_valid: "Contact Number not Valid",
    please_select_employment_status: "Please select Employment Status",
    please_select_job_status: "Please select Job Status",
    please_select_usergroup: "Please select usergroup",
    current_performance_plan_immediate_manager_has_been_changed: "Current Performance Plan / Immediate Manager has been changed.",
    selected_user_details_will_be_updated_click_ok_to_confirm: "Selected user details will be updated. Click OK to confirm.",
    user_details_has_been_updated_successfully: "User Details has been updated successfully.",
    this_will_generate_a_new_password_for_user_are_you_sure_to_continue: "This will generate a new password for user. Are you sure to continue?",
    generate_password: "Generate Password",
    newly_generated_password_for_user: "Newly generated password for user:",
    back: "Back",
    name: 'Name',
    all: "All",
    additional_description: "Additional Description",
    login_logs: "Login Logs",
    log_message: "Log Message",
    logged_on: "Logged On",
    user_management_logs: "User Management Logs",
    kpi_setting_logs: "KPI Setting Logs",
    cycle_logs: "Cycle Logs",
    module_logs: "Module Logs",
    copy_kpi_template: "Copy KPI Template",
    for_cycle: "For Cycle : ",
    user_group_name_is_required: "User Group name is required",
    muat_turun_fail_yang_diguna_di_dalam_kelas: "Download slide used in training classes.",
    KPI_target_setting_circular: "KPI Target Setting Circular",
    panduan_kompetensi_teknikal: "Technical Competency Guidebook",
    penetapan_KPI_dan_kompetensi_teknikal: "KPI Setting and Technical Competency",
    kandungan_masih_dalam_pembangunan: "Content is still under development",
    video2: "A Step By Step guide to start your KPI Setting and Technical Competency for Self and IMgr (content is still under development).",
    More_Videos_on_OBITS_System: "More Videos on Outcome-Based KPI",
    Outcome_Based_KPI_1: "Konsep Outcome-Based KPI (Siri 1-Analogi)",
    Outcome_Based_KPI_2: "Konsep Outcome-Based KPI (Siri 2-Pihak Berkepentingan)",
    Outcome_Based_KPI_3: "Konsep Outcome-Based KPI (Siri 2-Outcome, KPI & Sasaran)",
    Outcome_Based_KPI_Compress: "Konsep Outcome-Based KPI (Versi Penuh)",
    Proficiency_Level: "Proficiency Level Definition",
    KPI_Setting_for_Self: "OBITS: - Self",
    KPI_Setting_Video_IMgr: "OBITS: - IManager",
    proficiency_level_def: "Proficiency Level Definition Guidebook",
    Tech_Comp_Def : "Technical Competency Definition",
    Tech_Prof_Map: "Technical Proficiency Mapping Guideline",
    Strategic_Obj: "Strategic Objective Guideline",
    Strategic_Obj_Meas: "Strategic Objective Measure Guideline",
    Comp_Rate_Def: "Competency Rating Definition",
    KPI_Rt_Def: "KPI Rating Definition",
    have_technical_competency: "Have Technical Competency",
    inactive: "Inactive",
    staff_is_inactive: "Staff is inactive.",
    module_has_been_successfully_edited: "Module has been successfully edited",
    password: "Password",
    user_status: "User Status"
}