window.translations = {
    lang: "ms",
    "default": "Default",
    "delete": "Hapus",
    stakeholder_expectation_tooltip: "Jangkaan pihak berkepentingan terhadap produk dan perkhidmatan sesebuah Jabatan/ unit.",
    outcome_tooltip: "Hasil akhir yang ingin dicapai/ dipertingkatkan dalam mencapai aspirasi Jabatan/Bahagian di mana ia mestilah memberi impak positif kepada Pihak Berkepentingan",
    key_result_area_tooltip: "Bidang Keberhasilan Utama (KRA) yang dikenalpasti adalah selaras dan disokong oleh starategi berkaitan",
    strategy_tooltip: "Strategi atau aktiviti utama yang perlu dirancang dalam mempengaruhi pencapaian Penghasilan",
    indicator_tooltip: "Petunjuk aras prestasi utama (KPI) bagi mengukur tahap keberkesanan Penghasilan yang ingin dicapai",
    target_tooltip: "Julat menetapi sasaran",
    weightage_tooltip: "% keutamaan KPI berdasarkan Penghasilan",
    enabler_health_tooltip: "Petunjuk untuk mengukur pemangkin & keadaan/ kesihatan organisasi",
    target_enablerhealth_tooltip: "Sasaran untuk petunjuk bukan prestasi",
    login: "Login",
    logout: "Logout",
    staff_details: "Maklumat Pekerja",
    staff_name: "Nama Pekerja",
    email: "E-mail",
    contact_no: "No. Telefon",
    grade: "Gred",
    job: "Kefungsian Tugas",
    division: "Bahagian",
    department: "Jabatan",
    position: "Jawatan",
    position_level: "Kategori Jawatan",
    imanager_name: "Nama Penyelia",
    previous_imanager: "Penyelia Terdahulu",
    change_photo: "Tukar Foto",
    change_password: "Tukar Katalaluan",
    preferences: "Penetapan Bahasa",
    default_language: "Bahasa",
    error: "Ralat",
    cannot_retrieve_current_user_information: "Ralat mendapatkan maklumat pengguna",
    error_message: "Mesej ralat",
    welcome: "Selamat Datang",
    finish: "Tamat",
    kpi_setting_for: "Penetapan KPI untuk",
    the_kpi_setting_module_for_this_cycle_is_closed_kpi_setting_is_not_editable: "Modul Penetapan KPI untuk kitaran ini telah ditutup. Penetapan KPI tidak boleh dikemaskini lagi.",
    outcome_based_kpi: "KPI berdasarkan Penghasilan",
    add_new_kpi_and_enabler_health: "Tambah KPI dan Petunjuk Bukan Prestasi",
    add_new_enabler_health_only: "Tambah Petunjuk Bukan Prestasi Sahaja",
    stakeholder_expectation: "Jangkaan Pihak Berkepentingan",
    outcome: "Penghasilan",
    strategy_by_kra: "Strategi berdasarkan Bidang Keberhasilan Utama",
    enabler_health: "Petunjuk Bukan Prestasi",
    indicator: "Petunjuk",
    target: "Sasaran",
    indpeer: "Ind./<br>Pasukan",
    total_weightage: "Jumlah Pemberat",
    add_new_technical_competency: "Tambah Kompetensi Teknikal",
    technical_competency: "Kompetensi Teknikal",
    category: "Kategori",
    technical_label: "Label Teknikal",
    level: "Tahap",
    description: "Penerangan",
    action: "Tindakan",
    criteria_to_be_fulfilled_self: "Kriteria untuk Dipenuhi (Kendiri)",
    criteria_to_be_fulfilled_imanager: "Kriteria untuk Dipenuhi (Penyelia)",
    submit: "Hantar",
    define: "Muktamad",
    logs: "Log",
    print: "Cetak",
    kpi_setting: "Penetapan KPI",
    show: "Paparkan",
    kpi: "KPI",
    cascade: "Cascade",
    cascaded: "Cascaded",
    undo_cascade: "Batal Cascade",
    remove: "Hapus",
    individual: "Individu",
    peer: "Pasukan",
    yes: "Ya",
    no: "Tidak",
    kpi_cannot_be_submitted_if_these_criteria_are_not_met: "KPI tidak boleh dihantar sekiranya kriteria-kriteria ini tidak dipenuhi",
    kpi_cannot_be_defined_if_these_criteria_are_not_met: "KPI tidak boleh dimuktamadkan sekiranya kriteria-kriteria ini tidak dipenuhi",
    passed: "Lulus",
    not_passed: "Tidak Lulus",
    edit: "Kemaskini",
    show_profile: "Papar Profail",
    hide_profile: "Tutup Profail",
    draft: "Deraf",
    submitted: "Dihantar",
    defined: "Dimuktamadkan",
    is_required: "diperlukan",
    kpi_type: "Jenis KPI",
    stakeholder: "Pihak Berkepentingan",
    key_result_area_kra: "Bidang Keberhasilan Utama (KRA)",
    strategy_by_key_result_area: "Strategi berdasarkan Bidang Keberhasilan Utama",
    key_performance_indicator: "Petunjuk Prestasi Utama",
    target_kpi: "Sasaran KPI",
    lower_mt: "Aras Min. menepati sasaran",
    upper_mt: "Aras Maks. menepati sasaran",
    weightage: "Pemberat",
    save: "Hantar",
    select: "Pilih",
    some_error_occured_please_try_again: "Terdapat kesalahan input, sila periksa semula input yang dimasukkan.",
    there_are_some_errors_please_check_your_input: "Terdapat kesalahan input, sila periksa input yang dimasukkan.",
    some_error_occured_while_saving_enabler_health_please_try_again: "Kesilapan input berlaku semasa menyimpan Petunjuk Bukan Prestasi. Sila cuba semula.",
    kpi_has_been_successfully_added: "KPI telah berjaya ditambah.",
    administration: "Pentadbiran",
    cycle_management: "Pengurusan Kitaran",
    user_management: "Pengurusan Pengguna",
    usergroup_management: "Pengurusan Kumpulan Pengguna",
    user_registrations: "Pendaftaran Pengguna",
    forgotten_password: "Lupa Kata Laluan",
    email_template: "Templet Email",
    technical_categorylabel: "Kategori/Label Teknikal",
    job_management: "Pengurusan Bidang Tugas",
    position_management: "Pengurusan Kefungsian Tugas",
    grade_management: "Pengurusan Gred",
    divisiondepartment: "Bahagian/Jabatan",
    personnel_areasub_area: "Kawasan/Sub-Kawasan Pekerja",
    stakeholder_expectations: "Jangkaan Pihak Berkepentingan",
    position_level_management: "Pengurusan Kategori Jawatan",
    invalid_target_management: "Pengurusan Sasaran",
    email_queue: "Pengurusan Giliran Emel",
    system_configuration: "Konfigurasi Sistem",
    management_report: "Pengurusan Laporan",
    performance_plan_status: "Status Pelan Prestasi",
    not_submitted_self: "Belum Dihantar - Self",
    submitted_self: "Telah Dihantar - Self",
    incomplete_imgr: "Belum Selesai - Imgr",
    complete_imgr: "Selesai - Imgr",
    obits_cycle: "Kitaran OBITS",
    library: "Rujukan",
    user_training: "Latihan Pengguna",
    cycle_info: "Info Kitaran",
    edit_kpi_and_enabler_health: "Kemaskini KPI dan Petunjuk Bukan Prestasi",
    kpi_has_been_successfully_edited: "KPI telah berjaya dikemaskini",
    new_enabler_health_record_has_been_successfully_created: "Petunjuk Bukan Prestasi berjaya ditambah",
    text: "Teks",
    division_management: "Pengurusan Bahagian",
    subsidiary: "Anak Syarikat",
    active: "Aktif",
    deleted: "Dihapuskan",
    view_department: "Papar Jabatan",
    department_management: "Pengurusan Jabatan",
    type: "Jenis",
    supervisor: "Penyelia",
    send_emails_now: "Hantar Email Sekarang",
    subject: "Subjek",
    to: "Kepada",
    sent_on: "Dihantar pada",
    processed_on: "Diproses pada",
    created_on: "Diwujudkan pada",
    scheduled_on: "Dijadualkan pada",
    view_technical_competencies: "Papar Kompetensi Teknikal",
    technical_category: "Kategori Teknikal",
    proficiency_level: "Tahap Kecekapan",
    default_technical_competency_management: "Pengurusan Kompetensi Teknikal Default",
    add_technical_competency: "Tambah Kompetensi Teknikal",
    edit_technical_competency: "Kemaskini Kompetensi Teknikal",
    concept: "Concept",
    applying: "Applying",
    working: "Working",
    advanced: "Advanced",
    mastery: "Mastery",
    leading: "Leading",
    personnel_area_management: "Pengurusan Kawasan Pekerja",
    view_sub_areas: "Papar Sub-Kawasan",
    personnel_sub_area_management: "Pengurusan Sub-Kawasan Pekerja",
    area: "Kawasan",
    view_users: "Papar Pengguna",
    position_level_users_management: "Pengurusan Kategori Jawatan Pekerja",
    staff_no: "No. Pekerja",
    add_user_to_position_level: "Masukkan Pekerja ke Kategori Jawatan",
    search_for_a_staff_using_the_search_box_below: "Cari pekerja menggunakan kotak carian di bawah.",
    enter_staff_number_or_name: "Masukkan nombor atau nama pekerja",
    search: "Cari",
    some_error_occured_while_saving_enabler_health_indicatortarget_please_try_again: "Terdapat kesalahan input semasa menyimpan petunjuk/sasaran bagi Petunjuk Bukan Prestasi. Sila cuba semula.",
    add_enabler_health_only: "Tambah Petunjuk Bukan Prestasi Sahaja",
    you_must_have_at_least_one_indicatortarget: "Jumlah bilangan Petunjuk/Sasaran mestilah sekurang-kurangnya satu",
    edit_enabler_health_only: "Kemaskini Petunjuk Bukan Prestasi Sahaja",
    enabler_health_has_been_successfully_updated: "Petunjuk Bukan Prestasi berjaya dikemaskini",
    technical_category_management: "Pengurusan Kategori Teknikal",
    view_labels: "Papar Label",
    technical_label_management: "Pengurusan Label Teknikal",
    definition: "Definisi",
    datetime: "Tarikh/Masa",
    status: "Status",
    division_id: "ID Bahagian",
    division_name: "Nama Bahagian",
    phone_no: "No Telefon",
    remarks: "Justifikasi/Ulasan",
    create_user: "Tambah Pengguna",
    view_user: "Papar Pengguna",
    forgotten_password_logs: "Log Lupa Kata Laluan",
    password_reset: "Kata laluan diset semula",
    remarks_only: "Justifikasi/Ulasan sahaja",
    view_forgotten_password_logs: "Papar log lupa kata laluan",
    user_not_found: "Pengguna tidak ditemui",
    nric: "No K/P",
    reset_password: "Set Semula Kata Laluan",
    add_remarks_only: "Tambah Justifikasi/Ulasan Sahaja",
    user_login_type_is_active_directory_contact_email_administrator_for_password_management_operations: "Jenis login adalah Active Directory. Sila hubungi ICT Service Desk untuk operasi tukar kata laluan.",
    save_remarks: "Simpan Justifikasi/Ulasan",
    user_password_has_been_reset_to: "Kata laluan pengguna telah diset semula kepada",
    by: "Oleh",
    are_you_sure_to_reset_users_password: "Anda mahu meneruskan set semula kata laluan?",
    role: "Peranan",
    self: "Kendiri",
    imanager: "Penyelia",
    staff: "Pekerja",
    view: "Papar",
    kpi_templates: "Templet KPI",
    cycle: "Kitaran",
    current: "Terkini",
    completed: "Selesai",
    edit_usergroup: "Kemaskini Kumpulan Pengguna",
    create_new_usergroup: "Tambah Kumpulan Pengguna",
    usergroup_name: "Nama Kumpulan Pengguna",
    users: "Pengguna",
    technical_competency_has_been_successfully_added: "Kompetensi Teknikal telah berjaya ditambah",
    technical_competency_has_been_successfully_updated: "Kompetensi Teknikal telah berjaya dikemaskini",
    performance_plan_template: "Templet Pelan Prestasi",
    performance_template: "Templet KPI",
    view_performance_plan: "Papar Pelan Prestasi",
    kpi_template_cannot_be_copied_to_subordinates_if_these_criteria_are_not_met: "Templet KPI tidak boleh disalin kepada Pekerja Bawahan jika kriteria-kriteria ini tidak dipenuhi",
    error_calculating_weightage_please_try_again: "Kesalahan jumlah pemberat. Sila cuba semula.",
    kpi_has_been_successfully_deleted: "KPI telah berjaya dihapuskan.",
    technical_competency_has_been_successfully_deleted: "Kompetensi Teknikal telah berjaya dihapuskan.",
    enabler_health_has_been_successfully_deleted: "Petunjuk Bukan Prestasi telah berjaya dihapuskan.",
    create_new_user: "Tambah Pengguna Baru",
    user_type: "Jenis Pengguna",
    fetch_ad_information: "Tarik Maklumat AD",
    re_type_password: "Taip semula kata laluan",
    retire_date: "Tarikh Bersara",
    employment_status: "Status Penggajian Pekerja",
    job_status: "Status Pekerjaan",
    define_kpi_type: "Penetapan jenis KPI",
    enabled: "Dibenarkan",
    disabled: "Tidak Dibenarkan",
    usergroup: "Kumpulan Pengguna",
    assign_imgr: "Penetapan Penyelia",
    sub_area: "Sub-Kawasan",
    login_type: "Jenis Login",
    no_photo: "Tiada foto",
    edit_user: "Kemaskini Pengguna",
    never: "Tidak Pernah",
    last_login: "Login Terakhir",
    first_time_login: "Login Kali Pertama",
    job_details: "Maklumat Pekerjaan",
    change: "Tukar",
    performance_plans: "Pelan Prestasi",
    assign_new_immediate_manager: "Penetapan Penyelia Baru",
    sequence: "Turutan",
    set_as_current: "Set Terkini",
    personnel_area: "Kawasan Pekerja",
    personnel_sub_area: "Sub-Kawasan Pekerja",
    kpi_plan_template_successfully_copied_to_all_subordinates: "Templet KPI telah berjaya disalin kepada Pekerja Bawahan yang dipilih",
    failed_to_copy_kpi_plan_template_to_some_subordinates: "Gagal menyalin Templet KPI kepada Pekerja Bawahan yang dipilih",
    please_select_a_cycle: "Sila pilih kitaran",
    kpi_plan_has_been_successfully_submitted: "Pelan KPI telah berjaya dihantar.",
    kpi_plan_has_been_successfully_defined: "Pelan KPI telah berjaya dimuktamadkan.",
    you_have_reached_maximum_number_of_total_technical_competencies: "Maaf, anda telah mencapai jumlah maksimum Kompetensi Teknikal yang dibenarkan.",
    the_selected_peer_kpi_has_been_successfully_removed_from_your_subordinates_kpi_plan: "KPI Pasukan telah berjaya dihapuskan dari pelan KPI pekerja bawahan.",
    view_kpi_plan: "Papar KPI Pelan",
    rule_mandatory_fields: "Semua ruangan wajib perlu diisi",
    rule_individual_kpi_count: "KPI Individu - minimum : {0} maksimum: {1}",
    rule_peer_kpi_count: "KPI Peer - minimum : {0} maksimum: {1}",
    rule_technical_competency_count: "Kompetensi Teknikal - minimum : {0} maksimum: {1}",
    rule_individual_weight_total: "Jumlah Pemberat Individu - minimum: {0} maksimum: {1}",
    rule_all_kpi_count: "Jumlah KPI Pasukan - minimum: {0} maksimum: {1}",
    rule_weight_100: "Jumlah pemberat mestilah 100%",
    selected_kpi_will_be_deleted_click_ok_to_confirm: "Anda pasti untuk menghapuskan data KPI tersebut? Klik OK untuk teruskan.",
    selected_technical_competency_will_be_deleted_click_ok_to_confirm: "Anda pasti untuk menghapuskan data Kompetensi Teknikal tersebut? Klik OK untuk teruskan.",
    selected_enabler_health_will_be_deleted_click_ok_to_confirm: "Anda pasti untuk menghapuskan data Petunjuk Bukan Prestasi tersebut. Klik OK untuk teruskan.",
    kpi_plan_will_be_submitted_click_ok_to_confirm: "Pelan KPI akan dihantar untuk semakan Penyelia. Klik OK untuk teruskan.",
    kpi_plan_will_be_defined_click_ok_to_confirm: "Pelan KPI akan dimuktamadkan. Klik OK untuk teruskan.",
    alert_total_weightage_exceeds: "Perhatian: Jumlah keseluruhan pemberat telah melebihi ",
    alert_total_weightage_exceeds_100: "Perhatian: Jumlah keseluruhan pemberat tidak boleh melebihi 100%",
    job_is_required: "Sila masukkan Bidang Tugas",
    stakeholder_expectation_is_required: "Sila masukkan Jangkaan Pihak Berkepentingan",
    outcome_is_required: "Sila masukkan Penghasilan",
    key_result_area_is_required: "Sila masukkan Bidang Keberhasilan Utama",
    strategy_by_key_result_area_is_required: "Sila masukkan Strategi Mengikut KRA",
    key_performance_indicator_is_required: "Sila masukkan Petunjuk Prestasi Utama",
    lower_mt_is_required: "Sila masukkan Aras min Menepati Sasaran",
    upper_mt_is_required: "Sila masukkan Aras maks Menepati Sasaran",
    weightage_is_required: "Sila masukkan Pemberat",
    proficiency_level_is_required: "Sila masukkan Tahap Kecekapan",
    copy_kpi_plan_onto_subordinates: "Salin pelan KPI kepada Pekerja Bawahan",
    no_subordinates_selected: "Tiada pekerja bawahan yang dipilih",
    description_is_required: "Sila masukkan deskripsi",
    label_is_required: "Sila pilih Label",
    category_is_required: "Sila pilih Kategori",
    cascade_kpi_to_subordinates: "Cascade KPI kepada pekerja bawahan",
    cascade_kpi: "Cascade KPI",
    subordinates: "Pekerja bawahan",
    error_cascading_kpi_to: "Ralat sewaktu proses cascade kepada",
    copy_to_cycle: "Salin ke Kitaran",
    imgr_to_complete_staffs_kpi_setting: "IMgr perlu melengkapkan Penetapan KPI pekerja",
    attention_a_cascaded_kpi_has_been_selected_for_deletion_deletion_of_this_cascaded_kpi_will_subsequently_delete_the_same_kpi_at_your_subordinates_kpi_planning_and_the_affected_next_level_click_ok_to_confirm: "Perhatian! Cascaded KPI ingin dihapuskan. Penghapusan cascaded KPI ini akan menghapuskan KPI Pasukan pada pekerja bawahan anda, dan semua level pekerja bawahan yang membawa KPI ini. Klik OK untuk teruskan.",
    start_cycle_date: "Tarikh Mula Kitaran",
    end_cycle_date: "Tarikh Akhir Kitaran",
    start_module_date: "Tarikh Mula Modul",
    end_module_date: "Tarikh Akhir Modul",
    cycle_name_is_required: "Sila masukkan Nama Kitaran ",
    start_cycle_date_is_required: "Sila pilih Tarikh Mula Kitaran",
    maximum_weightage_for_self: "% maksimum pemberat untuk kendiri",
    peer_kpi_will_be_removed_from_your_subordinates_kpi_planning_and_subsequently_remove_the_same_kpi_at_the_affected_next_level_click_ok_to_confirm: "KPI Pasukan akan dihapuskan dari pelan KPI pekerja bawahan anda, dan juga semua level pekerja bawahan yang membawa KPI ini. Klik OK untuk teruskan.",
    kpi_and_technical_competency_have_been_successfully_copied: "KPI dan Kompetensi Teknikal telah berjaya disalin",
    kpi_has_been_successfully_cascaded_to: "KPI telah berjaya di-cascade kepada  ",
    technical_competency_has_been_successfully_edited: "Kompetensi Teknikal telah berjaya dikemaskini",
    weight: "Berat",
    end_cycle_date_is_required: "Sila pilih Tarikh Akhir Kitaran",
    a_new_cycle_will_be_created_click_ok_to_confirm: "Kitaran baru akan diwujudkan. Klik OK untuk teruskan",
    end_date_cannot_be_earlier_than_start_date: "Tarikh Akhir tidak boleh lebih awal daripada Tarikh Mula",
    cycle_has_been_saved_successfully: "Maklumat Kitaran telah berjaya dihantar.",
    add_open_to: "Tambah",
    edit_module: "Kemaskini Modul",
    open_to_category: "Kategori untuk Buka Sistem",
    select_a_department: "Sila pilih Bahagian",
    select_a_division: "Sila pilih Jabatan",
    select_a_position_level: "Sila pilih Tahap Jawatan",
    grade_type: "Gred",
    add_open_to_specification: "Simpan Maklumat Buka Sistem",
    open_to_specifications_has_been_successfully_added_to_module: "Maklumat Bukaan Sistem telah berjaya disimpan",
    edit_cycle: "Kemaskini Kitaran",
    update: "Kemaskini",
    kpi_rules_and_management: "Pengurusan dan Kriteria KPI",
    weightage_settings_unit: "Penetapan Pemberat (Unit %)",
    weightage_factor: "Faktor Pemberat ",
    weightage_fraction: "Pecahan Pemberat",
    numbers_divisible_by_5_separated_by_comma: "(nombor yang boleh dibahagi dengan 5, dijarakkan nilai seterusnya menggunakan simbol koma)",
    kpitechnical_competency_count: "Jumlah KPI/Kompetensi Teknikal",
    for_self: "bagi Kendiri",
    min: "Min",
    max: "Maks",
    individual_kpi_count: "Bilangan KPI Individu",
    technical_competency_total: "Jumlah Kompetensi Teknikal",
    individual_total_weightage: "Jumlah Pemberat KPI Individu",
    for_manager: "bagi Penyelia",
    peer_kpi_count: "Bilangan KPI Pasukan",
    kpi_total: "Bilangan  KPI",
    confirm: "Teruskan",
    modules: "Modul",
    selection_multi_rater: "Pemilihan Penilaian Pelbagai ",
    yeed: "YEED",
    epa_data_entry: "Kemasukan Data EPA",
    print_notification_letter: "Cetak Surat Makluman",
    appeal_registration: "Daftar Rayuan",
    appeal_registration_for_pa: "Daftar Rayuan (untuk PA)",
    appeal_data_entry: "Kemasukan Data Rayuan",
    print_appeal_letter: "Cetak Surat Rayuan",
    individual_development_plan: "Pelan Pembangunan Individu",
    minimum_kpi_total_is_required: "Sila masukkan Minimum Jumlah KPI",
    maximum_kpi_total_is_required: "Sila masukkan Maksimum Jumlah KPI",
    minimum_peer_kpi_is_required: "Sila masukkan Minimum KPI Pasukan",
    maximum_peer_kpi_is_required: "Sila masukkan Maksimum KPI Pasukan",
    minimum_weightage_is_required: "Sila masukkan Minimum Pemberat",
    maximum_weightage_is_required: "Sila masukkan Maksimum Pemberat",
    minimum_technical_competency_is_required: "Sila masukkan Minimum Kompetensi Teknikal",
    maximum_technical_competency_is_required: "Sila masukkan Maksimum Kompetensi Teknikal",
    minimum_individual_kpi_is_required: "Sila masukkan Minimum KPI Individu",
    maximum_individual_kpi_is_required: "Sila masukkan Maksimum KPI Individu",
    cycle_details_will_be_updated_click_ok_to_confirm: "Maklumat Kitaran akan dikemaskini. Klik OK untuk teruskan",
    cycle_has_been_updated_successfully: "Maklumat Kitaran telah berjaya disimpan.",
    technical_competency_total_max_value_must_be_greater_than_min_value: "Bilangan Kompetensi Teknikal: Nilai maksimum mestilah lebih besar daripada nilai minimum.",
    individual_total_weightage_max_value_must_be_greater_than_min_value: "Jumlah Pemberat Individu: Nilai maksimum mestilah lebih besar daripada nilai minimum.",
    individual_kpi_count_max_value_must_be_greater_than_min_value: "Bilangan KPI  Individu: Nilai maksimum mestilah lebih besar daripada nilai minimum.",
    peer_kpi_count_max_value_must_be_greater_than_min_value: "Bilangan KPI Pasukan: Nilai maksimum mestilah lebih besar daripada nilai minimum.",
    kpi_total_max_value_must_be_greater_than_min_value: "Jumlah KPI: Nilai maksimum mestilah lebih besar daripada nilai minimum.",
    cycle_rule_will_be_confirmed_click_ok_to_confirm: "Kriteria kitaran akan disimpan. Klik OK untuk teruskan.",
    cycle_rule_has_been_confirmed_successfully: "Kriteria kitaran akan disimpan. Klik OK untuk teruskan.",
    open_to: "Dibuka Kepada",
    open_to_specification: "Spesifikasi di buka kepada",
    specification: "Penerangan",
    start: "Mula",
    end: "Akhir",
    this_module_is_now: "Modul ini",
    for_this_cycle: "bagi Kitaran ini",
    upload_staff_data: "Muatnaik Data Pekerja",
    add_new_cycle: "Tambah Kitaran Baru",
    upload_data: "Muatnaik Data",
    staff_detail_file: "Fail Maklumat Pekerja",
    staff_manager_file: "Fail Pekerja-Penyelia",
    start_processing: "Sedang diproses",
    sending_emails: "Email sedang dihantar..",
    current_password: "Kata Laluan Semasa",
    new_password: "Kata Laluan Baru",
    re_type_new_password_for_confirmation: "Taip semula Kata Laluan baru untuk pengesahan",
    change: "Set Semula",
    password_cannot_be_empty: "Sila masukkan Kata Laluan",
    new_password_and_password_confirmation_must_be_the_same: "Kata Laluan dan Pengesahan Kata Laluan mestilah sama",
    password_has_been_changed_successfully: "Kata Laluan baru telah berjaya disimpan",
    upload_photo_jpgjpeg_max_size_100kb: "Muatnaik Gambar (.jpg/.jpg, saiz maks 100kb)",
    please_upload_jpg_files_only: "Sila muatnaik fail jenis JPEG",
    file_size_more_than_100kb_is_not_allowed: "Saiz fail melebihi 100kb tidak boleh dimuatnaik",
    default_technical_competency_has_been_successfully_edited: "Kompetensi teknikal default telah berjaya dikemaskini",
    cycle_information: "Maklumat Kitaran",
    content_is_coming_soon: "Kandungan masih dalam pembangunan",
    documents: "Dokumen",
    frequently_asked_questions_faq: "Frequently Asked Questions (FAQ)",
    click_to_download_file: "Klik untuk muat turun fail",
    circular: "Pekeliling",
    user_manual_malay: "Manual Pengguna",
    kpi_settings_for_self: "Penetapan KPI bagi Peranan Kendiri",
    kpi_settings_for_manager: "Penetapan KPI bagi Peranan Penyelia",
    user_manual_english: "Manual Pengguna (English)",
    overview: "Pengenalan",
    introducing_the_new_kpi_framework_and_information_about_obits: "Kenali framework baru KPI dan maklumat berkenaan sistem OBITS",
    video_and_demos: "Video dan Demonstrasi",
    watch_interactive_video_tutorials_and_product_highlights: "Tonton video interaktif dan demonstrasi sistem",
    faqs_and_documents: "FAQ dan Dokumen",
    get_circular_information_user_manual_and_answers_to_your_faqs: "Dapatkan maklumat FAQ , pekeliling dan panduan pengguna",
    obits_introduction: "Pengenalan OBITS",
    to_view_this_video_please_enable_javascript_and_consider_upgrading_to_a_web_browser_that: "Untuk mainkan video ini, sila aktifkan fungsi Javascript di browser dan gunakan browser yang",
    supports_html5_video: "menyokong video HTML5",
    user_successfully_assigned_to_position_level: "Maklumat Peringkat Jawatan berjaya disimpan",
    no_records_found: "Rekod tidak dijumpai",
    please_enter_keywords_to_search: "Masukkan kata kunci untuk carian",
    a_new_user_group_will_be_created_click_ok_to_confirm: "Kumpulan Pengguna baru akan diwujudkan. Klik OK untuk teruskan",
    usergroup_was_successfully_created_assigned_access_rights_by_clicking_on_the_checkboxes: "Kumpulan Pengguna berjaya diwujudkan. Tetapkan hak akses dengan klik pada kotak semak",
    user_group_detail_will_be_updated_click_ok_to_confirm: "Kumpulan Pengguna akan dikemaskini. Klik OK untuk teruskan.",
    role_was_successfully_updated: "Peranan telah berjaya dikemaskini",
    e_mail_template: "Templet Emel",
    template_type: "Jenis Templet",
    select_template_type: "Pilih jenis templet",
    subject_template: "Subjek Templet",
    content_template: "Kandungan Templet",
    preview: "Lihat",
    save_template: "Simpan Templet",
    variables: "Pembolehubah",
    select_a_template_type_to_see_description: "Pilih jenis templet untuk melihat huraian..",
    notification_when_a_module_is_starting: "Pemberitahuan apabila modul dibuka.",
    notification_when_a_module_is_ending: "Pemberitahuan apabila modul ditutup. ",
    notification_when_a_plan_status_changed_from_completed_to_submitted_because_of_peer_kpi_deletion_or_other_factors: "Pemberitahuan apabila status pelan diubah daripada Selesai kepada Dihantar disebabkan penghapusan KPI Pasukan atau faktor lain.",
    password_reset_email_when_user_go_through_the_forgot_password_feature: "Set semula kata laluan sewaktu pengguna menggunakan fungsi Lupa Kata Laluan.",
    notification_for_administrators_when_a_new_user_registered_into_the_system: "Pemberitahuan kepada Pentadbir Sistem apabila pengguna baru didaftarkan di dalam sistem.",
    error_while_parsing_template: "Ralat sewaktu templet emel dihantar",
    email_template_has_been_saved_successfully: "Templet emel berjaya disimpan.",
    remarks_has_been_saved_successfully: "Justifikasi/Ulasan berjaya disimpan",
    assign_immediate_manager: "Tugaskan IMgr",
    manage_user: "Pentadbiran Pengguna",
    current_immediate_manager: "IMgr terkini",
    select_cycle: "Pilih kitaran:",
    search_for_a_new_immediate_manager_using_the_search_box_below: "Cari IMgr baru menggunakan medan carian di bawah.",
    search: "Carian",
    sub_area: "Sub-Area",
    are_you_sure_to_assign_immediate_manager_for_user: "Anda pasti untuk menetapkan IMgr kepada pengguna: ",
    current_imgr: "IMgr terkini:",
    assign_to_imgr: "Ditugaskan di bawah Imgr:",
    user: "Pengguna:",
    immediate_manager_assigned_successfully: "Maklumat IMgr berjaya disimpan",
    enter_department: "Masukkan jabatan...",
    change_department: "Tukar Jabatan",
    department_changed_successfully: "Penukaran Jabatan berjaya.",
    change_grade: "Tukar Gred",
    enter_grade: "Masukkan gred…",
    grade_changed_successfully: "Gred telah berjaya ditukar",
    change_immediate_manager: "Tukar IMgr",
    current_immediate_manager: "IMgr Semasa",
    are_you_sure_to_change_immediate_manager_for_user: "Anda pasti untuk Menukar IMgr bagi pengguna : ",
    new_imgr: "IMgr baharu: ",
    immediate_manager_changed_successfully: "IMgr telah berjaya ditukar",
    change_job: "Tukar Pekerjaan",
    job_changed_successfully: "Pekerjaan berjaya ditukar",
    password_changed_successfully: "Kata laluan berjaya ditukar",
    change_personnel_sub_area: "Tukar Personnel Sub-Area",
    enter_personnel_area_or_sub_area: "Masukkan Personnel Area atau Sub-Area",
    personnel_sub_area_changed_successfully: "Personnel Sub-Area berjaya ditukar",
    change_position: "Tukar Jawatan",
    enter_position: "Masukkan Jawatan",
    position_changed_successfully: "Jawatan telah berjaya ditukar. ",
    change_position_level: "Tukar Peringkat Jawatan",
    enter_position_level: "Masukkan Peringkat Jawatan",
    position_level_changed_successfully: "Peringkat Jawatan telah berjaya ditukar",
    fetching_user_information_from_active_directory: "Pengambilan maklumat pengguna dari Direktori Aktif…",
    cannot_find_staff_with_id: "Pekerja bernombor ID = __ tidak dijumpai. ",
    already_registered_in_obits: "Telah berdaftar di dalam OBITS",
    information_successfully_fetched_from_active_directory: "Maklumat berjaya diambil dari Direktori Aktif.",
    password_and_password_verification_must_be_the_same: "Kata Laluan baru mesti sama seperti kata laluan pengesahan. ",
    new_user_will_be_created_click_ok_to_confirm: "Pengguna baru akan didaftarkan. Klik OK untuk meneruskan.",
    user_successfully_created_please_proceed_by_setting_job_details: "Pengguna baru telah berjaya didaftarkan. Sila teruskan dengan kemaskini Maklumat Pekerjaan dan tetapkan Imgr",
    fullname_is_required: "Sila masukkan Nama penuh",
    contact_number_not_valid: "Nombor telefon tidak sah",
    please_select_employment_status: "Sila pilih Status Penggajian",
    please_select_job_status: "Sila pilih Status Pekerjaan",
    please_select_usergroup: "Sila pilih Kumpulan Pengguna. ",
    current_performance_plan_immediate_manager_has_been_changed: "Perancangan Prestasi Semasa/ IMgr berjaya ditukar.",
    selected_user_details_will_be_updated_click_ok_to_confirm: "Maklumat pengguna telah berjaya dikemaskini. Klik OK untuk teruskan.",
    user_details_has_been_updated_successfully: "Maklumat pengguna telah berjaya dikemaskini",
    this_will_generate_a_new_password_for_user_are_you_sure_to_continue: "Kata laluan baharu untuk pengguna akan dijana. Anda pasti untuk teruskan? ",
    generate_password: "Jana kata laluan",
    newly_generated_password_for_user: "Kata laluan bagi pekerja tersebut telah berjaya dijanakan:",
    back: "Kembali",
    name: 'Nama',
    all: "Semua",
    additional_description: "Penerangan Tambahan",
    login_logs: "Log Login",
    log_message: "Log Mesej",
    logged_on: "Log Masuk Pada",
    user_management_logs: "Log Pegurusan Pengguna",
    kpi_setting_logs: "Log Penetapan KPI",
    cycle_logs: "Log Kitaran",
    module_logs: "Log Modul",
    copy_kpi_template: "Salin Templet KPI",
    for_cycle: "Untuk Kitaran :",
    user_group_name_is_required: "Sila masukkan nama kumpulan pengguna",
    muat_turun_fail_yang_diguna_di_dalam_kelas: "Muat turun fail yang digunakan di dalam kelas latihan",
    panduan_kompetensi_teknikal: "Panduan Kompetensi Teknikal",
    KPI_target_setting_circular: "Pekeliling Sasaran Penetapan KPI",
    penetapan_KPI_dan_kompetensi_teknikal: "Penetapan KPI dan Kompetensi Teknikal",
    kandungan_masih_dalam_pembangunan: "Kandungan masih dalam pembangunan",
    video2: "Demonstrasi penggunaan sistem bagi Penetapan KPI dan Kompetensi Teknikal bagi peranan Self dan IMgr (kandungan masih dalam pembangunan).",
    More_Videos_on_OBITS_System: "Lagi Video Mengenai Outcome-Based KPI",
    Outcome_Based_KPI_1: "Konsep Outcome-Based KPI (Siri 1-Analogi)",
    Outcome_Based_KPI_2: "Konsep Outcome-Based KPI (Siri 2-Pihak Berkepentingan)",
    Outcome_Based_KPI_3: "Konsep Outcome-Based KPI (Siri 2-Outcome, KPI & Sasaran)",
    Outcome_Based_KPI_Compress: "Konsep Outcome-Based KPI (Versi Penuh)",
    Proficiency_Level: "Definisi Tahap Kecekapan Teknikal",
    KPI_Setting_for_Self: "OBITS: - Peranan Individu",
    KPI_Setting_Video_IMgr: "OBITS: - Peranan Penyelia",
    proficiency_level_def: "Definisi Tahap Kecekapan Teknikal",
    Tech_Comp_Def : "Definisi Kecekapan Teknikal",
    Tech_Prof_Map: "Panduan Pemetaan Kecekapan Teknikal",
    Strategic_Obj: "Panduan Objektif Strategik",
    Strategic_Obj_Meas: "Panduan Ukuran Objektif Strategik",
    Comp_Rate_Def: "Definisi Penilaian Kompetensi",
    KPI_Rt_Def: "Definisi Penilaian KPI",
    have_technical_competency: "Ada Kompetensi Teknikal",
    inactive: "Tidak Active",
    staff_is_inactive: "Pekerja ini sudah tidak aktif.",
    module_has_been_successfully_edited: "Modul telah berjaya dikemaskini",
    password: "Katalaluan",
    user_status: "Status Pengguna"
}